name: rllab3
channels:
    - https://conda.anaconda.org/kne 
    - https://conda.anaconda.org/tlatorre 
    - https://conda.anaconda.org/cjs14
    - https://conda.anaconda.org/menpo
    - jjhelmus
    - soumith
dependencies:
    - python==3.5.2
    - numpy==1.12.0
    - scipy
    - path.py
    - python-dateutil
    - joblib==0.10.3
    - mako
    - ipywidgets
    - numba
    - flask
    - pybox2d
    - pygame
    - h5py
    - matplotlib
    - opencv3=3.1.0
    - scikit-learn
    - mpi4py
    - pandas
    - pip:
        - Pillow
        - atari-py
        - pyprind
        - ipdb
        - boto3
        - PyOpenGL
        - nose2
        - pyzmq
        - tqdm
        - msgpack-python
        - mujoco_py
        - cached_property
        - line_profiler
        - cloudpickle
        - Cython
        - redis    
        - -r https://raw.githubusercontent.com/Lasagne/Lasagne/master/requirements.txt
        - https://github.com/Lasagne/Lasagne/archive/master.zip
        - awscli
        - git+https://github.com/openai/gym.git@v0.7.4#egg=gym
        - pyglet
        - git+https://github.com/neocxi/prettytensor.git
        - jupyter
        - progressbar2
        - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.1-cp35-cp35m-linux_x86_64.whl; 'linux' in sys_platform
        - https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow_gpu-1.0.1-py3-none-any.whl; sys_platform == 'darwin'
        - numpy-stl==2.2.0
        - nibabel==2.1.0
        - pylru==1.0.9
        - hyperopt
        - polling
